# Generated by Django 6.0.2 on 2026-02-21 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_categoria_cesta_padaria_endereco_produto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, help_text='Telefone do usuário', max_length=20, null=True, verbose_name='Telefone')),
                ('cpf', models.CharField(blank=True, help_text='CPF do usuário', max_length=11, null=True, verbose_name='CPF')),
                ('data_nascimento', models.DateField(blank=True, help_text='Data de nascimento do usuário', null=True, verbose_name='Data de Nascimento')),
                ('user', models.OneToOneField(help_text='Usuário do perfil', on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
